POST http://localhost:8080/fetch/artists
Content-Type: application/json

{
  "artists": [
    "Kali uchis",
    "Lady gaga",
    "Lorde",
    "Rina sawayama",
    "kero kero bonito",
    "brockhampton",
    "radiohead",
    "kaykatranda",
    "michel telo",
    "artic monekys",
    "clairo",
    "blackpink",
    "seu jorge"
  ]
}

###
