POST http://localhost:8080/fetch/artists
Content-Type: application/json

{
  "artists": [
    "Kali uchis",
    "Lady gaga",
    "Lorde",
    "Rina sawayama",
    "kero kero bonito",
    "brockhampton",
    "radiohead",
    "kaykatranda",
    "michel telo",
    "artic monekys",
    "clairo",
    "blackpink",
    "seu jorge"
  ]
}

###

POST http://localhost:8080/fetch/albums
Content-Type: application/json

{
  "albums": [
    {
      "name": "hot pink",
      "artist": "doja cat"
    },
    {
      "name": "k-12",
      "artist": "melanie martinez"
    }
  ]
}

###

POST http://localhost:8080/fetch/tracks
Content-Type: application/json

{
  "tracks": [
    {
      "name": "replay",
      "artist": "lady gaga",
      "album": "chromatica"
    },
    {
      "name": "play date",
      "artist": "melanie martinez",
      "album": "cry baby"
    },
    {
      "name": "CYBER STOCKHOLM SYNDROME",
      "artist": "Rina sawayama",
      "album": "rina"
    },
    {
      "name": "say so",
      "artist": "doja cat"
    }
  ]
}

###
